# Generated by Django 4.0.2 on 2022-02-02 07:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Individu',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=12, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=90, null=True)),
                ('prenom', models.CharField(max_length=90, null=True)),
                ('age', models.CharField(max_length=10, null=True)),
                ('date_nais', models.DateField()),
                ('lieu', models.CharField(max_length=30, null=True)),
                ('sex', models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme'), ('Garçon', 'Garçon'), ('Fille', 'Fille')], max_length=30, null=True)),
                ('situation', models.CharField(choices=[('Marié', 'Marié'), ('Divorcé', 'Divorcé'), ('Célibataire', 'Célibataire')], max_length=30, null=True)),
            ],
        ),
    ]
