# Generated by Django 4.0.2 on 2022-02-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='individu',
            name='nom_mere',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='individu',
            name='nom_pere',
            field=models.CharField(max_length=90, null=True),
        ),
    ]
