# Generated by Django 4.0.2 on 2022-02-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individu', '0002_individu_nom_mere_individu_nom_pere'),
    ]

    operations = [
        migrations.AddField(
            model_name='individu',
            name='nom_epous',
            field=models.CharField(max_length=90, null=True),
        ),
    ]
