# Generated by Django 4.0.1 on 2022-02-03 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individu', '0003_individu_nom_epous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individu',
            name='date_nais',
            field=models.DateField(blank=True, null=True),
        ),
    ]
