# Generated by Django 4.0.1 on 2022-02-12 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('individu', '0004_alter_individu_date_nais'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individu',
            name='age',
        ),
        migrations.RemoveField(
            model_name='individu',
            name='nom_epous',
        ),
        migrations.RemoveField(
            model_name='individu',
            name='nom_mere',
        ),
        migrations.RemoveField(
            model_name='individu',
            name='nom_pere',
        ),
        migrations.RemoveField(
            model_name='individu',
            name='situation',
        ),
    ]
