# Generated by Django 4.0.1 on 2022-02-12 10:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('individu', '0005_remove_individu_age_remove_individu_nom_epous_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='individu',
            name='id_ep',
            field=models.IntegerField(default=0, max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='individu',
            name='id',
            field=models.IntegerField(default=uuid.uuid4, max_length=12, primary_key=True, serialize=False),
        ),
    ]
