# Generated by Django 4.0.1 on 2022-02-12 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individu', '0006_individu_id_ep_alter_individu_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individu',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
