# Generated by Django 3.2.8 on 2022-02-12 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individu', '0007_alter_individu_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individu',
            name='id_ep',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
