# Generated by Django 3.2.8 on 2022-02-27 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individu', '0009_alter_individu_id_ep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individu',
            name='id_ep',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
