# Generated by Django 3.2.8 on 2022-03-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individu', '0010_alter_individu_id_ep'),
    ]

    operations = [
        migrations.AddField(
            model_name='individu',
            name='age',
            field=models.IntegerField(default=0, null=0),
        ),
    ]
