# Generated by Django 3.2.8 on 2022-03-11 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('individu', '0011_individu_age'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='individu',
            table='individus',
        ),
    ]
