# Generated by Django 3.2.8 on 2022-03-12 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('individu', '0012_alter_individu_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individu',
            name='age',
        ),
    ]
