# Generated by Django 3.2.8 on 2022-03-15 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individu', '0018_alter_individu_id_ep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individu',
            name='id_ep',
            field=models.IntegerField(default=0),
        ),
    ]
