# Generated by Django 3.2.8 on 2022-03-15 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individu', '0024_alter_individu_id_ep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individu',
            name='id_ep',
            field=models.CharField(default='0', max_length=5, null=True),
        ),
    ]
