# Generated by Django 3.2.8 on 2022-03-15 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('individu', '0028_alter_individu_id_ep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individu',
            name='age',
        ),
    ]
