# Generated by Django 3.2.8 on 2022-03-16 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('individu', '0030_individu_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individu',
            name='age',
        ),
    ]
