# Generated by Django 3.2.8 on 2022-03-07 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('individu', '0011_individu_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enfant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_mere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='individu.individu')),
            ],
        ),
    ]
