# Generated by Django 3.2.8 on 2022-03-07 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('individu', '0011_individu_age'),
        ('enfant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enfant',
            name='id_enfant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_enfant', to='individu.individu'),
        ),
        migrations.AlterField(
            model_name='enfant',
            name='id_mere',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_mere', to='individu.individu'),
        ),
    ]
