# Generated by Django 3.2.8 on 2022-03-11 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enfant', '0002_auto_20220307_1735'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='enfant',
            table='enfants',
        ),
    ]
