# Generated by Django 3.2.8 on 2022-03-12 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enfant', '0003_alter_enfant_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enfant',
            old_name='id_enfant',
            new_name='nom_enfant',
        ),
        migrations.RenameField(
            model_name='enfant',
            old_name='id_mere',
            new_name='nom_mere',
        ),
    ]
