# Generated by Django 3.2.8 on 2022-03-13 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enfant', '0004_auto_20220312_0849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enfant',
            name='nom_enfant',
        ),
    ]
