# Generated by Django 3.2.8 on 2022-03-13 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('individu', '0015_remove_individu_age'),
        ('enfant', '0005_remove_enfant_nom_enfant'),
    ]

    operations = [
        migrations.AddField(
            model_name='enfant',
            name='nom_enfant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_enfant', to='individu.individu'),
        ),
    ]
