# Generated by Django 3.2.8 on 2022-03-18 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('individu', '0031_remove_individu_age'),
        ('enfant', '0006_enfant_nom_enfant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enfant',
            name='nom_enfant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nom_enfant', to='individu.individu'),
        ),
        migrations.AlterField(
            model_name='enfant',
            name='nom_mere',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nom_mere', to='individu.individu'),
        ),
    ]
